services:
  postgres:
    image: postgres:16
    container_name: inventory_pg_db
    env_file:
      - .env
    ports:
      - 5434:5432
    networks:
      - inventory_network
    volumes:
      - inventory_pg_data:/var/lib/postgresql/data

networks:
  inventory_network:
    driver: bridge

volumes:
  inventory_pg_data:
